USE [ERP_JEVEN]
GO

/****** Object:  Table [HM].[CRM_Provinces]    Script Date: 13.05.2018 19:05:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [HM].[CRM_Provinces](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[RegionId] [int] NOT NULL,
 CONSTRAINT [PK_CRM_Provinces] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [HM].[CRM_Provinces]  WITH CHECK ADD  CONSTRAINT [FK_CRM_Provinces_CRM_Regions] FOREIGN KEY([RegionId])
REFERENCES [HM].[CRM_Regions] ([Id])
GO

ALTER TABLE [HM].[CRM_Provinces] CHECK CONSTRAINT [FK_CRM_Provinces_CRM_Regions]
GO

