//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Silnie typizowana klasa zasobów do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub rekompiluj projekt Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Zwraca buforowane wystąpienie składnika ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej silnie typizowanej klasy zasobów.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Architekt.
        /// </summary>
        internal static string CustomerType_Architect {
            get {
                return ResourceManager.GetString("CustomerType_Architect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Firma consultingowa.
        /// </summary>
        internal static string CustomerType_ConsultingCompany {
            get {
                return ResourceManager.GetString("CustomerType_ConsultingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Firma gastronomiczna.
        /// </summary>
        internal static string CustomerType_GastronomyCompany {
            get {
                return ResourceManager.GetString("CustomerType_GastronomyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generalny wykonawca.
        /// </summary>
        internal static string CustomerType_GeneralContractor {
            get {
                return ResourceManager.GetString("CustomerType_GeneralContractor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wykonawca instalacji.
        /// </summary>
        internal static string CustomerType_InstallationContractor {
            get {
                return ResourceManager.GetString("CustomerType_InstallationContractor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szef kuchni.
        /// </summary>
        internal static string CustomerType_KitchentChef {
            get {
                return ResourceManager.GetString("CustomerType_KitchentChef", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Technolog kuchni.
        /// </summary>
        internal static string CustomerType_KitchenTechnologist {
            get {
                return ResourceManager.GetString("CustomerType_KitchenTechnologist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Diler Mareno.
        /// </summary>
        internal static string CustomerType_MarenoDealer {
            get {
                return ResourceManager.GetString("CustomerType_MarenoDealer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inwestor sieciowy.
        /// </summary>
        internal static string CustomerType_NetworkInvestor {
            get {
                return ResourceManager.GetString("CustomerType_NetworkInvestor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sanepid.
        /// </summary>
        internal static string CustomerType_Sanepid {
            get {
                return ResourceManager.GetString("CustomerType_Sanepid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inwestor pojedynczy.
        /// </summary>
        internal static string CustomerType_SingleInvestor {
            get {
                return ResourceManager.GetString("CustomerType_SingleInvestor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inspektor nadzoru.
        /// </summary>
        internal static string CustomerType_SupervisionInspector {
            get {
                return ResourceManager.GetString("CustomerType_SupervisionInspector", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Diler Synergia.
        /// </summary>
        internal static string CustomerType_SynergiaDealer {
            get {
                return ResourceManager.GetString("CustomerType_SynergiaDealer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Projektant wentylacji.
        /// </summary>
        internal static string CustomerType_VentilationDesigner {
            get {
                return ResourceManager.GetString("CustomerType_VentilationDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hurtownia wentylacyjna.
        /// </summary>
        internal static string CustomerType_VentilationWholesaler {
            get {
                return ResourceManager.GetString("CustomerType_VentilationWholesaler", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gastronomia.
        /// </summary>
        internal static string InstallationObjectType_Gastronomy {
            get {
                return ResourceManager.GetString("InstallationObjectType_Gastronomy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inne.
        /// </summary>
        internal static string InstallationObjectType_Other {
            get {
                return ResourceManager.GetString("InstallationObjectType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Administrator.
        /// </summary>
        internal static string UserRole_Administrator {
            get {
                return ResourceManager.GetString("UserRole_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ofertownik Synergia.
        /// </summary>
        internal static string UserRole_HoodOffers {
            get {
                return ResourceManager.GetString("UserRole_HoodOffers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Menadżer.
        /// </summary>
        internal static string UserRole_Manager {
            get {
                return ResourceManager.GetString("UserRole_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Panel Mareno.
        /// </summary>
        internal static string UserRole_Mareno {
            get {
                return ResourceManager.GetString("UserRole_Mareno", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mareno i Raporty.
        /// </summary>
        internal static string UserRole_MarenoReporter {
            get {
                return ResourceManager.GetString("UserRole_MarenoReporter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Raportownik.
        /// </summary>
        internal static string UserRole_Reporter {
            get {
                return ResourceManager.GetString("UserRole_Reporter", resourceCulture);
            }
        }
    }
}
