//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.CRM_CampaignContacts = new HashSet<CampaignContact>();
            this.CRM_CampaignFiles = new HashSet<CampaignFile>();
            this.CRM_Campaigns1 = new HashSet<Campaign>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedByUserId { get; set; }
        public int OwnerUserId { get; set; }
        public string MessageSubject { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> CopiedFromCampaignId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignContact> CRM_CampaignContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignFile> CRM_CampaignFiles { get; set; }
        public virtual User CRM_Users { get; set; }
        public virtual User CRM_Users1 { get; set; }
        public virtual User CRM_Users2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> CRM_Campaigns1 { get; set; }
        public virtual Campaign CRM_Campaigns2 { get; set; }
    }
}
