//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int Id { get; set; }
        public string WelcomeText { get; set; }
        public bool OverrideUserWelcomeText { get; set; }
        public string SmallBirthdayText { get; set; }
        public string BigBirthdayText { get; set; }
        public string OrderEmailRecipients { get; set; }
        public Nullable<int> HoodOfferStartingNumber { get; set; }
        public Nullable<int> HoodFinalOfferLogoFileId { get; set; }
        public Nullable<int> HoodFinalOfferStartingNumber { get; set; }
        public string HoodOrderEmailRecipients { get; set; }
        public string SubmittedMonthlyReportEmailRecipients { get; set; }
        public Nullable<int> HoodOrderZMJStartingNumber { get; set; }
        public Nullable<int> HoodOrderWNRStartingNumber { get; set; }
        public Nullable<int> HoodOrderZNStartingNumber { get; set; }
        public Nullable<int> HoodOrderANSStartingNumber { get; set; }
        public Nullable<int> HoodOrderZCAStartingNumber { get; set; }
        public Nullable<int> HoodOrderSMStartingNumber { get; set; }
        public Nullable<int> HoodOrderZSTStartingNumber { get; set; }
        public int JevenCustomerId { get; set; }
    
        public virtual File CRM_Files { get; set; }
    }
}
