//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.CRM_CampaignContacts = new HashSet<CampaignContact>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string MobilePhone { get; set; }
        public string LandlinePhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CustomerType { get; set; }
        public string Position { get; set; }
        public string Interests { get; set; }
        public bool BirthdayReminder { get; set; }
        public string Attitude { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LastContact { get; set; }
        public Nullable<byte> Status { get; set; }
        public int OffersCompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedByUserId { get; set; }
        public int OwnerUserId { get; set; }
    
        public virtual OfferCompany CRM_OfferCompanies { get; set; }
        public virtual User CRM_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignContact> CRM_CampaignContacts { get; set; }
    }
}
