//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NIP { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartment { get; set; }
        public string Type { get; set; }
        public string Marker { get; set; }
        public Nullable<bool> CDim_B2B { get; set; }
        public string REGON { get; set; }
        public Nullable<double> ReceivablesPLN { get; set; }
        public Nullable<double> ReceivablesWAL { get; set; }
        public Nullable<double> Receivables { get; set; }
        public string PaymentFormName { get; set; }
        public double LimitValue { get; set; }
        public string LimitCurency { get; set; }
        public string Email { get; set; }
        public string OrderCurrency { get; set; }
        public string Address { get; set; }
    }
}
