//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int Id { get; set; }
        public Nullable<int> ParId { get; set; }
        public string Code { get; set; }
        public string Photo1 { get; set; }
        public Nullable<int> ParParId { get; set; }
        public Nullable<int> Lp1 { get; set; }
    }
}
