//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public double ValueGross { get; set; }
        public double ValueToPay { get; set; }
        public Nullable<int> KhId { get; set; }
        public string DocumentName { get; set; }
        public double ValueNet { get; set; }
        public string khkod { get; set; }
        public string File { get; set; }
    }
}
