//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_SYNERGIAEntities : DbContext
    {
        public ERP_SYNERGIAEntities()
            : base("name=ERP_SYNERGIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> CRM_Users { get; set; }
        public virtual DbSet<Group> vCRM_Grupy { get; set; }
        public virtual DbSet<PhotoPath> vCRM_FotoSc { get; set; }
        public virtual DbSet<InstallationObject> S_OBIEKTY { get; set; }
        public virtual DbSet<DocumentPath> vCRM_DokSc { get; set; }
        public virtual DbSet<Customer> vCRM_Firmy { get; set; }
        public virtual DbSet<Invoice> vCRM_FirmyFVS { get; set; }
        public virtual DbSet<WZDoc> vCRM_FirmyWZ { get; set; }
        public virtual DbSet<File> CRM_Files { get; set; }
        public virtual DbSet<OfferCompany> CRM_OfferCompanies { get; set; }
        public virtual DbSet<Contact> CRM_Contacts { get; set; }
        public virtual DbSet<OfferElement> CRM_OfferElements { get; set; }
        public virtual DbSet<OrderElement> CRM_OrderElements { get; set; }
        public virtual DbSet<PersonalProduct> CRM_PersonalProducts { get; set; }
        public virtual DbSet<Province> CRM_Provinces { get; set; }
        public virtual DbSet<Region> CRM_Regions { get; set; }
        public virtual DbSet<SC> CRM_SC { get; set; }
        public virtual DbSet<CampaignContact> CRM_CampaignContacts { get; set; }
        public virtual DbSet<CampaignFile> CRM_CampaignFiles { get; set; }
        public virtual DbSet<Campaign> CRM_Campaigns { get; set; }
        public virtual DbSet<Offer> CRM_Offers { get; set; }
        public virtual DbSet<Order> CRM_Orders { get; set; }
        public virtual DbSet<CustomerType> CRM_CustomerType { get; set; }
        public virtual DbSet<OfferCompanyCustomerType> CRM_OfferCompanyCustomerType { get; set; }
        public virtual DbSet<Language> CRM_Languages { get; set; }
        public virtual DbSet<Configuration> CRM_Configuration { get; set; }
        public virtual DbSet<UserRole> CRM_UserRoles { get; set; }
        public virtual DbSet<UserRoleDict> CRM_UserRolesDict { get; set; }
        public virtual DbSet<vCRM_FirmyNaleznosci> vCRM_FirmyNaleznosci { get; set; }
        public virtual DbSet<vCRM_TowaryDok> vCRM_TowaryDok { get; set; }
        public virtual DbSet<vCRM_TowaryPow> vCRM_TowaryPow { get; set; }
        public virtual DbSet<Product> vCRM_Produkty { get; set; }
    
        public virtual ObjectResult<pCRM_Customers_GridGetCustomersList_Result> pCRM_Customers_GridGetCustomersList(Nullable<bool> showOfferCompanies, Nullable<bool> showSymfoniaCompanies, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var showOfferCompaniesParameter = showOfferCompanies.HasValue ?
                new ObjectParameter("ShowOfferCompanies", showOfferCompanies) :
                new ObjectParameter("ShowOfferCompanies", typeof(bool));
    
            var showSymfoniaCompaniesParameter = showSymfoniaCompanies.HasValue ?
                new ObjectParameter("ShowSymfoniaCompanies", showSymfoniaCompanies) :
                new ObjectParameter("ShowSymfoniaCompanies", typeof(bool));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Customers_GridGetCustomersList_Result>("pCRM_Customers_GridGetCustomersList", showOfferCompaniesParameter, showSymfoniaCompaniesParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Objects_GridGetInstallationObjectsList_Result> pCRM_Objects_GridGetInstallationObjectsList(Nullable<int> userId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Objects_GridGetInstallationObjectsList_Result>("pCRM_Objects_GridGetInstallationObjectsList", userIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Invoices_GridGetInvoicesList_Result> pCRM_Invoices_GridGetInvoicesList(Nullable<int> userId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Invoices_GridGetInvoicesList_Result>("pCRM_Invoices_GridGetInvoicesList", userIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Users_GridGetUsersList_Result> pCRM_Users_GridGetUsersList(string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Users_GridGetUsersList_Result>("pCRM_Users_GridGetUsersList", searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Contacts_GridGetContactsList_Result> pCRM_Contacts_GridGetContactsList(Nullable<int> userId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Contacts_GridGetContactsList_Result>("pCRM_Contacts_GridGetContactsList", userIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Offers_GridGetOffersList_Result> pCRM_Offers_GridGetOffersList(Nullable<int> userId, Nullable<byte> status, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Offers_GridGetOffersList_Result>("pCRM_Offers_GridGetOffersList", userIdParameter, statusParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_OfferElements_GridGetOfferElementsList_Result> pCRM_OfferElements_GridGetOfferElementsList(Nullable<int> userId, Nullable<int> offerId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var offerIdParameter = offerId.HasValue ?
                new ObjectParameter("OfferId", offerId) :
                new ObjectParameter("OfferId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_OfferElements_GridGetOfferElementsList_Result>("pCRM_OfferElements_GridGetOfferElementsList", userIdParameter, offerIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_PersonalProducts_GridGetPersonalProductsList_Result> pCRM_PersonalProducts_GridGetPersonalProductsList(Nullable<int> userId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_PersonalProducts_GridGetPersonalProductsList_Result>("pCRM_PersonalProducts_GridGetPersonalProductsList", userIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Orders_GridGetOrdersList_Result> pCRM_Orders_GridGetOrdersList(Nullable<int> userId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Orders_GridGetOrdersList_Result>("pCRM_Orders_GridGetOrdersList", userIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_OrderElements_GridGetOrderElementsList_Result> pCRM_OrderElements_GridGetOrderElementsList(Nullable<int> userId, Nullable<int> orderId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_OrderElements_GridGetOrderElementsList_Result>("pCRM_OrderElements_GridGetOrderElementsList", userIdParameter, orderIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_MonthlyReport_GridGetMonthlyReportsList_Result> pCRM_MonthlyReport_GridGetMonthlyReportsList(Nullable<int> userId, Nullable<bool> showAllSubmittedReports, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var showAllSubmittedReportsParameter = showAllSubmittedReports.HasValue ?
                new ObjectParameter("ShowAllSubmittedReports", showAllSubmittedReports) :
                new ObjectParameter("ShowAllSubmittedReports", typeof(bool));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_MonthlyReport_GridGetMonthlyReportsList_Result>("pCRM_MonthlyReport_GridGetMonthlyReportsList", userIdParameter, showAllSubmittedReportsParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_ActivitiesAnalysis_GridGetActivitiesAnalysisList_Result> pCRM_ActivitiesAnalysis_GridGetActivitiesAnalysisList(Nullable<int> userId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_ActivitiesAnalysis_GridGetActivitiesAnalysisList_Result>("pCRM_ActivitiesAnalysis_GridGetActivitiesAnalysisList", userIdParameter, startDateParameter, endDateParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_DetailedAnalysis_GridGetDetailedAnalysisList_Result> pCRM_DetailedAnalysis_GridGetDetailedAnalysisList(Nullable<int> userId, Nullable<byte> column, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var columnParameter = column.HasValue ?
                new ObjectParameter("Column", column) :
                new ObjectParameter("Column", typeof(byte));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_DetailedAnalysis_GridGetDetailedAnalysisList_Result>("pCRM_DetailedAnalysis_GridGetDetailedAnalysisList", userIdParameter, columnParameter, startDateParameter, endDateParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Campaigns_GridGetCampaignsList_Result> pCRM_Campaigns_GridGetCampaignsList(string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Campaigns_GridGetCampaignsList_Result>("pCRM_Campaigns_GridGetCampaignsList", searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_CampaignContacts_GridGetCampaignContactsList_Result> pCRM_CampaignContacts_GridGetCampaignContactsList(Nullable<int> campaignId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_CampaignContacts_GridGetCampaignContactsList_Result>("pCRM_CampaignContacts_GridGetCampaignContactsList", campaignIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_CampaignContacts_GridGetAvailableContactsList_Result> pCRM_CampaignContacts_GridGetAvailableContactsList(Nullable<int> campaignId, string contactType, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(int));
    
            var contactTypeParameter = contactType != null ?
                new ObjectParameter("ContactType", contactType) :
                new ObjectParameter("ContactType", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_CampaignContacts_GridGetAvailableContactsList_Result>("pCRM_CampaignContacts_GridGetAvailableContactsList", campaignIdParameter, contactTypeParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_CampaignFiles_GridGetCampaignFilesList_Result> pCRM_CampaignFiles_GridGetCampaignFilesList(Nullable<int> campaignId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_CampaignFiles_GridGetCampaignFilesList_Result>("pCRM_CampaignFiles_GridGetCampaignFilesList", campaignIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodPartsPriceList_GridGetHoodPartsPriceListList_Result> pCRM_HoodPartsPriceList_GridGetHoodPartsPriceListList(string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodPartsPriceList_GridGetHoodPartsPriceListList_Result>("pCRM_HoodPartsPriceList_GridGetHoodPartsPriceListList", searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodOfferElements_GridGetHoodOfferElementsList_Result> pCRM_HoodOfferElements_GridGetHoodOfferElementsList(Nullable<int> userId, Nullable<int> hoodOfferId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var hoodOfferIdParameter = hoodOfferId.HasValue ?
                new ObjectParameter("HoodOfferId", hoodOfferId) :
                new ObjectParameter("HoodOfferId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodOfferElements_GridGetHoodOfferElementsList_Result>("pCRM_HoodOfferElements_GridGetHoodOfferElementsList", userIdParameter, hoodOfferIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_WeeklyPlans_GridGetWeeklyPlansList_Result> pCRM_WeeklyPlans_GridGetWeeklyPlansList(Nullable<int> userId, Nullable<bool> showAllWeeklyReports, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var showAllWeeklyReportsParameter = showAllWeeklyReports.HasValue ?
                new ObjectParameter("ShowAllWeeklyReports", showAllWeeklyReports) :
                new ObjectParameter("ShowAllWeeklyReports", typeof(bool));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_WeeklyPlans_GridGetWeeklyPlansList_Result>("pCRM_WeeklyPlans_GridGetWeeklyPlansList", userIdParameter, showAllWeeklyReportsParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_WZDocs_GridGetWZDocsList_Result> pCRM_WZDocs_GridGetWZDocsList(Nullable<int> userId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_WZDocs_GridGetWZDocsList_Result>("pCRM_WZDocs_GridGetWZDocsList", userIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodOfferElements_GridGetAllHoodOfferElementsList_Result> pCRM_HoodOfferElements_GridGetAllHoodOfferElementsList(Nullable<int> userId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodOfferElements_GridGetAllHoodOfferElementsList_Result>("pCRM_HoodOfferElements_GridGetAllHoodOfferElementsList", userIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodOffers_GridGetHoodOffersList_Result> pCRM_HoodOffers_GridGetHoodOffersList(Nullable<int> userId, string statuses, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var statusesParameter = statuses != null ?
                new ObjectParameter("Statuses", statuses) :
                new ObjectParameter("Statuses", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodOffers_GridGetHoodOffersList_Result>("pCRM_HoodOffers_GridGetHoodOffersList", userIdParameter, statusesParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodFinalOffers_GridGetHoodFinalOffersList_Result> pCRM_HoodFinalOffers_GridGetHoodFinalOffersList(Nullable<int> userId, Nullable<byte> status, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodFinalOffers_GridGetHoodFinalOffersList_Result>("pCRM_HoodFinalOffers_GridGetHoodFinalOffersList", userIdParameter, statusParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodFinalOfferElements_GridGetHoodFinalOfferElementsList_Result> pCRM_HoodFinalOfferElements_GridGetHoodFinalOfferElementsList(Nullable<int> userId, Nullable<int> hoodFinalOfferId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var hoodFinalOfferIdParameter = hoodFinalOfferId.HasValue ?
                new ObjectParameter("HoodFinalOfferId", hoodFinalOfferId) :
                new ObjectParameter("HoodFinalOfferId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodFinalOfferElements_GridGetHoodFinalOfferElementsList_Result>("pCRM_HoodFinalOfferElements_GridGetHoodFinalOfferElementsList", userIdParameter, hoodFinalOfferIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodOrders_GridGetHoodOrdersList_Result> pCRM_HoodOrders_GridGetHoodOrdersList(Nullable<int> userId, Nullable<byte> type, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(byte));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodOrders_GridGetHoodOrdersList_Result>("pCRM_HoodOrders_GridGetHoodOrdersList", userIdParameter, typeParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_HoodOrderElements_GridGetHoodOrderElementsList_Result> pCRM_HoodOrderElements_GridGetHoodOrderElementsList(Nullable<int> userId, Nullable<int> hoodOrderId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var hoodOrderIdParameter = hoodOrderId.HasValue ?
                new ObjectParameter("HoodOrderId", hoodOrderId) :
                new ObjectParameter("HoodOrderId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_HoodOrderElements_GridGetHoodOrderElementsList_Result>("pCRM_HoodOrderElements_GridGetHoodOrderElementsList", userIdParameter, hoodOrderIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Customers_GridGetUsersList_Result> pCRM_Customers_GridGetUsersList(Nullable<int> customerId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Customers_GridGetUsersList_Result>("pCRM_Customers_GridGetUsersList", customerIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<Nullable<double>> pCRM_GetCurrencyCourse(string curr)
        {
            var currParameter = curr != null ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("pCRM_GetCurrencyCourse", currParameter);
        }
    
        public virtual ObjectResult<string> pCRM_GetKHOrderCurrency(Nullable<int> idKH)
        {
            var idKHParameter = idKH.HasValue ?
                new ObjectParameter("idKH", idKH) :
                new ObjectParameter("idKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pCRM_GetKHOrderCurrency", idKHParameter);
        }
    
        public virtual ObjectResult<string> pCRM_GetKHTWCurrency(Nullable<int> idTW, Nullable<int> idKH)
        {
            var idTWParameter = idTW.HasValue ?
                new ObjectParameter("idTW", idTW) :
                new ObjectParameter("idTW", typeof(int));
    
            var idKHParameter = idKH.HasValue ?
                new ObjectParameter("idKH", idKH) :
                new ObjectParameter("idKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pCRM_GetKHTWCurrency", idTWParameter, idKHParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> pCRM_GetKHTWPrice(Nullable<int> idTW, Nullable<int> idKH)
        {
            var idTWParameter = idTW.HasValue ?
                new ObjectParameter("idTW", idTW) :
                new ObjectParameter("idTW", typeof(int));
    
            var idKHParameter = idKH.HasValue ?
                new ObjectParameter("idKH", idKH) :
                new ObjectParameter("idKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("pCRM_GetKHTWPrice", idTWParameter, idKHParameter);
        }
    
        public virtual ObjectResult<pCRM_Products_GridGetDocumentsList_Result> pCRM_Products_GridGetDocumentsList(string productIds, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var productIdsParameter = productIds != null ?
                new ObjectParameter("ProductIds", productIds) :
                new ObjectParameter("ProductIds", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Products_GridGetDocumentsList_Result>("pCRM_Products_GridGetDocumentsList", productIdsParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    
        public virtual ObjectResult<pCRM_Products_GridGetProductsList_Result> pCRM_Products_GridGetProductsList(Nullable<byte> pairType, Nullable<int> parentProductId, string search, Nullable<byte> sortField, string sortDirection, Nullable<int> start, Nullable<int> lenght, ObjectParameter recordsTotal)
        {
            var pairTypeParameter = pairType.HasValue ?
                new ObjectParameter("PairType", pairType) :
                new ObjectParameter("PairType", typeof(byte));
    
            var parentProductIdParameter = parentProductId.HasValue ?
                new ObjectParameter("ParentProductId", parentProductId) :
                new ObjectParameter("ParentProductId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var sortFieldParameter = sortField.HasValue ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(byte));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("Lenght", lenght) :
                new ObjectParameter("Lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCRM_Products_GridGetProductsList_Result>("pCRM_Products_GridGetProductsList", pairTypeParameter, parentProductIdParameter, searchParameter, sortFieldParameter, sortDirectionParameter, startParameter, lenghtParameter, recordsTotal);
        }
    }
}
