//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.CRM_OfferElements = new HashSet<OfferElement>();
            this.CRM_Offers1 = new HashSet<Offer>();
            this.CRM_Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public string City { get; set; }
        public string OfferNumber { get; set; }
        public Nullable<int> LogoFileId { get; set; }
        public int SellerFirmaId { get; set; }
        public Nullable<int> CustomerOfferCompanyId { get; set; }
        public byte Status { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public decimal CatalogValue { get; set; }
        public int OwnerUserId { get; set; }
        public decimal ValueAfterPrimatyDiscount { get; set; }
        public decimal FinalValueAfterAllDiscounts { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> InstallationObjectObiektyId { get; set; }
        public Nullable<int> OfferPdfFileId { get; set; }
        public Nullable<int> CopiedFromOfferId { get; set; }
        public bool IsPrepayment { get; set; }
        public byte PrepaymentPercent { get; set; }
        public byte PaymentType { get; set; }
        public byte DeliveryTimeDays { get; set; }
        public byte GuaranteeYears { get; set; }
        public bool WithEmptyInstallationObjectObiektyId { get; set; }
        public bool HasOnlyInnoSavaProducts { get; set; }
        public byte DeliveryType { get; set; }
        public decimal DeliveryCost { get; set; }
    
        public virtual File CRM_Files { get; set; }
        public virtual File CRM_Files1 { get; set; }
        public virtual OfferCompany CRM_OfferCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferElement> CRM_OfferElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> CRM_Offers1 { get; set; }
        public virtual Offer CRM_Offers2 { get; set; }
        public virtual User CRM_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> CRM_Orders { get; set; }
    }
}
