//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferCompany()
        {
            this.CRM_Contacts = new HashSet<Contact>();
            this.S_OBIEKTY = new HashSet<InstallationObject>();
            this.CRM_Offers = new HashSet<Offer>();
            this.CRM_Orders = new HashSet<Order>();
            this.CRM_OfferCompanyCustomerType = new HashSet<OfferCompanyCustomerType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string NIP { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int OwnerUserId { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedByUserId { get; set; }
        public string Discription { get; set; }
        public Nullable<short> StartYear { get; set; }
        public Nullable<System.DateTime> LastContact { get; set; }
        public string Challenge { get; set; }
        public string DeliveredMaterials { get; set; }
        public Nullable<byte> Status { get; set; }
        public string CustomerType { get; set; }
        public Nullable<int> ErpId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> CRM_Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationObject> S_OBIEKTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> CRM_Offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> CRM_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferCompanyCustomerType> CRM_OfferCompanyCustomerType { get; set; }
        public virtual User CRM_Users { get; set; }
        public virtual User CRM_Users1 { get; set; }
        public virtual User CRM_Users2 { get; set; }
    }
}
