//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferCompanyCustomerType
    {
        public int Id { get; set; }
        public int CustomerTypeId { get; set; }
        public int OfferCompanyId { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int OwnerUserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CustomerType CRM_CustomerType { get; set; }
        public virtual OfferCompany CRM_OfferCompanies { get; set; }
        public virtual User CRM_Users { get; set; }
        public virtual User CRM_Users1 { get; set; }
        public virtual User CRM_Users2 { get; set; }
    }
}
