//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderElement
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ProduktId { get; set; }
        public decimal CatalogPriceNet { get; set; }
        public decimal Discount { get; set; }
        public decimal PriceAfterDiscountNet { get; set; }
        public decimal FinalValueNet { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public int OwnerUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int CreatedFromOfferElementId { get; set; }
        public byte DeliveryTimeDays { get; set; }
    
        public virtual User CRM_Users { get; set; }
        public virtual User CRM_Users1 { get; set; }
        public virtual User CRM_Users2 { get; set; }
        public virtual Order CRM_Orders { get; set; }
    }
}
