//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Um { get; set; }
        public double Weight { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Dimensions { get; set; }
        public string Photo1 { get; set; }
        public Nullable<int> Lp1 { get; set; }
        public Nullable<int> ParGroupId { get; set; }
        public Nullable<double> PriceNet { get; set; }
        public string ProdPack { get; set; }
        public string ProdQuantityDesc { get; set; }
    }
}
