//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CRM_Contacts = new HashSet<Contact>();
            this.CRM_OrderElements = new HashSet<OrderElement>();
            this.CRM_OrderElements1 = new HashSet<OrderElement>();
            this.CRM_OrderElements2 = new HashSet<OrderElement>();
            this.CRM_PersonalProducts = new HashSet<PersonalProduct>();
            this.CRM_PersonalProducts1 = new HashSet<PersonalProduct>();
            this.CRM_PersonalProducts2 = new HashSet<PersonalProduct>();
            this.CRM_CampaignContacts = new HashSet<CampaignContact>();
            this.CRM_CampaignContacts1 = new HashSet<CampaignContact>();
            this.CRM_CampaignFiles = new HashSet<CampaignFile>();
            this.CRM_CampaignFiles1 = new HashSet<CampaignFile>();
            this.CRM_Campaigns = new HashSet<Campaign>();
            this.CRM_Campaigns1 = new HashSet<Campaign>();
            this.CRM_Campaigns2 = new HashSet<Campaign>();
            this.CRM_Offers = new HashSet<Offer>();
            this.CRM_Orders = new HashSet<Order>();
            this.CRM_Orders1 = new HashSet<Order>();
            this.CRM_Orders2 = new HashSet<Order>();
            this.CRM_OfferCompanyCustomerType = new HashSet<OfferCompanyCustomerType>();
            this.CRM_OfferCompanyCustomerType1 = new HashSet<OfferCompanyCustomerType>();
            this.CRM_OfferCompanyCustomerType2 = new HashSet<OfferCompanyCustomerType>();
            this.CRM_OfferCompanies = new HashSet<OfferCompany>();
            this.CRM_OfferCompanies1 = new HashSet<OfferCompany>();
            this.CRM_OfferCompanies2 = new HashSet<OfferCompany>();
            this.CRM_UserRoles = new HashSet<UserRole>();
            this.CRM_UserRoles1 = new HashSet<UserRole>();
            this.CRM_UserRoles2 = new HashSet<UserRole>();
            this.S_OBIEKTY = new HashSet<InstallationObject>();
            this.S_OBIEKTY1 = new HashSet<InstallationObject>();
            this.S_OBIEKTY2 = new HashSet<InstallationObject>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public byte Role { get; set; }
        public string Salt { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string WelcomeText { get; set; }
        public Nullable<System.DateTime> BirthdayDate { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> OfferLogoFileId { get; set; }
        public string Boss { get; set; }
        public string Position { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Phone { get; set; }
        public bool IsPasswordChangeRequired { get; set; }
        public Nullable<int> AvatarFileId { get; set; }
        public bool CanSeeSymfoniaCompanies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> CRM_Contacts { get; set; }
        public virtual File CRM_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderElement> CRM_OrderElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderElement> CRM_OrderElements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderElement> CRM_OrderElements2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalProduct> CRM_PersonalProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalProduct> CRM_PersonalProducts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalProduct> CRM_PersonalProducts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignContact> CRM_CampaignContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignContact> CRM_CampaignContacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignFile> CRM_CampaignFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignFile> CRM_CampaignFiles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> CRM_Campaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> CRM_Campaigns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> CRM_Campaigns2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> CRM_Offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> CRM_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> CRM_Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> CRM_Orders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferCompanyCustomerType> CRM_OfferCompanyCustomerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferCompanyCustomerType> CRM_OfferCompanyCustomerType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferCompanyCustomerType> CRM_OfferCompanyCustomerType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferCompany> CRM_OfferCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferCompany> CRM_OfferCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferCompany> CRM_OfferCompanies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> CRM_UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> CRM_UserRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> CRM_UserRoles2 { get; set; }
        public virtual File CRM_Files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationObject> S_OBIEKTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationObject> S_OBIEKTY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationObject> S_OBIEKTY2 { get; set; }
    }
}
