//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergia.B2B.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCRM_FirmyNaleznosci
    {
        public Nullable<int> ContractorId { get; set; }
        public double ReceivablesPLN { get; set; }
        public double ReceivablesWAL { get; set; }
    }
}
